### ISSUE TITLE
unable to attempt to carry world over from 1.7.3a

### ISSUE THREAD

**Issue by lag42** [The-Nexus-Project/Limitless-3#33]
### Describe your issue, what happened?
the screen in this screenshot below will not let me into the world, if i click safe mode it will just unselect it after a few minutes of freezing and title screen will of course put me back at the title screen

if this is closed as wontfix i won't complain and i'll just start a new world and leave the old one as a victim of bad timing to start the pack, but if it's something easy to fix i'd like to do it

### To Reproduce

1. Create a new world on modpack version 1.7.3a
2. Quit the game
3. Update the pack to 1.7.4
4. Load the world again
5. See error

### Expected behavior
i would be able to load my world that i started a couple days ago despite the mismatches, maybe some minor issues would occur but it would at least let me try

### Screenshots
![2020-11-16](https://user-images.githubusercontent.com/22325011/99272475-75156180-27ed-11eb-87dd-c9c407b8bbde.png)

### Crash Reports & Logs (Don't paste entire crash reports here.)
https://gist.github.com/lag42/350d72f36a3dd85853111b0c78256201

### Affected Version

- Pack Version: 1.7.3a & 1.7.4
- On a server?: no

**Comment by Gbergz** [comment]
Need logs

**Comment by lag42** [comment]
https://gist.github.com/lag42/350d72f36a3dd85853111b0c78256201
here you go, sorry for not including it in the actual issue at first, i convinced myself it didn't apply

**Comment by Gbergz** [comment]
I think those logs got cut off, try drag and drop the logs here

**Comment by lag42** [comment]
[latest.log](https://github.com/The-Nexus-Project/Limitless-3/files/5547294/latest.log)

**Comment by Gbergz** [comment]
Just wondering if you did a complete reinstall of the instance when you updated to 1.7.4?

**Comment by Gbergz** [comment]
Nevermind, just reproduced this issue. I'll investigate

**Comment by lag42** [comment]
but you were right about me not doing a clean reinstall, that is something i should have tried first anyways
(though i can reproduce this with a clean reinstall on my computer too)

**Comment by Gbergz** [comment]
I've now reposted v1.7.4, and the datapack error / world loading errors should be solved. Give it a try. But do a clean install.

https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/files/3113479

**Comment by lag42** [comment]
works like a charm, thank you

**Comment by lag42** [comment]
actually i did discover that the nether and the end got unregisted somehow in that world, they didn't show up in "/forge dimensions" and the portals did not go anywhere but the folder still existed

i can't seem to fix this with any amount of nbt editing or grafting files onto a new world so this might just be a breaking update entirely, thank you for your help though

**Comment by Gbergz** [comment]
You can fix this by having a backup of your world before bringing it to 1.16.4 (1.7.4), then downloading NBT Explorer, open the Level.dat & level.dat(old) in NBT Explorer from the pre-update. Open another NBT Explorer and then open Level.dat & level.dat(old) again from the new world on 1.16.4(1.7.4). Copy the_nether & the_end under the 'dimensions' tab. to the world where they are missing.


Or just follow this image:
![worldsmissing](https://user-images.githubusercontent.com/26634554/99529040-7b4b3f80-299f-11eb-95f3-bcd950a12946.png)

**Comment by Gbergz** [comment]
These instructions are rough, but I hope you understand. 

I've also confirmed this is working as I did it to fix the Official Server's Nether & The End.

Hope it works for you aswell. And any others.

**Comment by lag42** [comment]
i already started a new world that i am quite happy with, but hopefully this does help others

**Comment by Gbergz** [comment]
Ah alright, sorry you had to do that!
